export const BUSINESS_THEME_TOKENS = {
  bg: {
    page: '#FAFAFB',
    sidebar: '#F5F7FB',
    surface: '#FFFFFF',
    surfaceSoft: '#FBFCFE',
    surfaceMuted: '#F8FAFC',
    surfaceSubtle: '#F7F9FC',
  },
  text: {
    title: '#171B24',
    heading: '#1E2330',
    body: '#1F2937',
    secondary: '#667085',
    muted: '#8F96A3',
    placeholder: '#A0A6B2',
  },
  border: {
    default: '#E7EBF1',
    soft: '#E8EAF0',
    subtle: '#E8ECF2',
  },
  radius: {
    xs: '8px',
    sm: '10px',
    md: '12px',
    lg: '14px',
    xl: '16px',
    xxl: '18px',
    shell: '20px',
    input: '22px',
    pill: '999px',
  },
  font: {
    family: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
} as const;

export const BUSINESS_THEME_VARS = {
  bgPage: 'var(--oc-bg-page)',
  bgSidebar: 'var(--oc-bg-sidebar)',
  bgSurface: 'var(--oc-bg-surface)',
  bgSurfaceSoft: 'var(--oc-bg-surface-soft)',
  bgSurfaceMuted: 'var(--oc-bg-surface-muted)',
  bgSurfaceSubtle: 'var(--oc-bg-surface-subtle)',
  textTitle: 'var(--oc-text-title)',
  textHeading: 'var(--oc-text-heading)',
  textBody: 'var(--oc-text-body)',
  textSecondary: 'var(--oc-text-secondary)',
  textMuted: 'var(--oc-text-muted)',
  textPlaceholder: 'var(--oc-text-placeholder)',
  borderDefault: 'var(--oc-border-default)',
  borderSoft: 'var(--oc-border-soft)',
  borderSubtle: 'var(--oc-border-subtle)',
  radiusShell: 'var(--oc-radius-shell)',
  radiusInput: 'var(--oc-radius-input)',
  radiusPill: 'var(--oc-radius-pill)',
  shellPageBg: 'var(--oc-shell-page-bg)',
  shellSidebarBg: 'var(--oc-shell-sidebar-bg)',
  cardBg: 'var(--oc-card-bg)',
  inputBg: 'var(--oc-input-bg)',
  sidebarItemHoverBg: 'var(--oc-sidebar-item-hover-bg)',
  sidebarItemSelectedBg: 'var(--oc-sidebar-item-selected-bg)',
  shellBorder: 'var(--oc-shell-border)',
  fontFamily: BUSINESS_THEME_TOKENS.font.family,
} as const;
